# Generated by Django 5.0rc1 on 2024-06-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_logik_and_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
