# Generated by Django 5.0rc1 on 2024-06-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_logik_and_template', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateField(),
        ),
    ]
